[package]
name = "script"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
strip-ansi-escapes = "0.2.0"
terminal-menu = "3.0.0"
time = "0.3.36"
typst = "0.11.1"
