[package]
name = "add-entry"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.9.0"
crossterm = "0.25.0"
dateparser = "0.2.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
terminal-menu = "3.0.0"
typst = "0.11.1"
